#!/bin/bash
set -e

echo "=== CUSTOM ASSEMBLE START ==="

cd /tmp/src

chmod +x gradlew

./gradlew clean build -x test

echo "Copying JAR..."

mkdir -p /deployments

cp build/libs/*.jar /deployments/app.jar

echo "=== CUSTOM ASSEMBLE DONE ==="